### ISSUE TITLE
Geo assets window

### ISSUE THREAD

**Issue by someonemax** [hiddify/hiddify-next#1039]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The menu option to open the window used to update geo assets is no longer visible in v1.5.2

### Minimal Reproducible Example (MRE)

The menu option to open the window used to update geo assets is no longer visible in v1.5.2

### Version

v1.5.2

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by mhmd-hb** [comment]
i can confirm that on 1.5.2 android 14, there is no routing assets section in app settings.
and if if it's not a bug and the app sets rules automatically like sing-box, i should inform you that there's something buggy in there. because it's not working like sing-box and all configs fails to connect.
please bring back routing assets settings and add an option to add custom assets too.

**Comment by hiddify-com** [comment]
It is removed!
we will create a better alternative soon
