### ISSUE TITLE
Free warp

### ISSUE THREAD

**Issue by karimi12** [hiddify/hiddify-next#1055]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Free warp in Hiddifynext is a logical problem for progress this application and other tools because this feature is against monetary VPNs

Why a VPN seller should interduce HiddifyNext  to their users because after this action users can use free warp and never buy VPN?

I think this feature should be removed 

### Minimal Reproducible Example (MRE)

nothing

### Version

v1.5.6

### Platform/OS

Android, Windows, macOS, Linux, iOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MMDPrh** [comment]
Hello,

I think the real issue is not with using a free VPN but with what you're saying. Do you think this is a game sir? Making money from people who have are extremely limited and have no other choice is not fair. Why should these people pay for something that shouldn't be a problem in the first place? VPNs should be for people who want extra security and already have good internet, not for those who just want some freedom, we already have big companies to offer that, people selling it is not necessary and reasonable.
I'm a teenager and I don't have any money because I'm still studying and can't work yet. Are you saying I should buy a VPN from people in social medias like telegram or instagram that charge a lot and might not even offer good service, or worse, might be scams? Why should I deal with another problem that shouldn't even exist? I'm already stressed trying to keep my interner and VPN working every day. Now you're saying I should worry about finding money to pay for a VPN that should be free? Please think about what you're saying.

**Comment by karimi12** [comment]
الان محمد جان چی داری می گی؟!
عزیز من یک نرم افزار باید یک رویکرد مشخص داشته باشه مثلا های دیفای بشه
ابزار مثلا گذر از فیلترینگ که  تعداد زیادی پروتکل داره
اما نباید وسط راه هدفش عوض کنه
کسی نگفت شما باید VPN بخری یا نخری منظورم این که های دیفای نباید با اپش
وارد این بازی ها بشه و باید بی طرف باشه و هدفش روی افزایش تعداد کاربران
باشه
یک ابزار جامع مثل های دیفای لازم که تمامی افراد چه کسانی که vpn  می خرند و
می فروشند چه کسانی که خودشون سرور دارند باید بتونن ازش استفاده کنند با و در
هم کردن یک VPN  داخلی داخل های دیفای بخشی از جمعیت هدف حذف می شه و این کار
به خود هادیفای و هدفش ضربه می زنه از اون طرف مشکلات بیشتری وارد محصول می
کنه چرا که باید از این به بعد ایشو های مربوط به وارپ رایگان هم حل کنند.

من یکبار به دوستان های دیفای هم گفتم همین سیستمی که الان دارند با یک تغییر
کوچک بخشیش پولی کنند مثلا اگر بیشتر از 100 یوزر تعریف شد برای تعریف یوزر
101 به بعد ماهیانه 5 دلار با کریپتو بگیرند اینجوری می تونن متمرکز روی این
محصول و هدفش کار کنند یا اینکه کلا یک ابزار پولی جدید از صفر بنا کنند اما
به هدفشان که دسترسی مردم به اینترنت آزاد هست لطمه ای نزند که دوستان برای
این موضوع انتخاب کردن اصلا وارد موضوعات تجاری نشوند.
به همین دلیل الان من هم این موضوع مطرح کردم که دوستان ناخواسته دارن وارد
این موضوعات می شوند و از هدف اصلیشون دور می شوند.
