### ISSUE TITLE
[FR] Use "Proxy" to replace the "Disconnect" text in the tray

### ISSUE THREAD

**Issue by aucub** [hiddify/hiddify-next#194]
### Feature description

The software seems to use a check mark in the tray to indicate whether the proxy is connected, and the displayed text is "Disconnect". Although these words represent actions that the user can perform, they may not be meaningful in some cases. It is recommended to use "Proxy" text or the selected node name instead.

**Comment by problematicconsumer** [comment]
One of our main goals with Hiddify Next is to provider an easy-to-use experience for newbies and hide the complexities in more advanced sections of the app. Since these users might not know the difference between proxy, tun etc. we've used a more generalized term, “connect”. In this way, users can easily relate to the options and more demanding users will have access to more in-depth settings like service mode, config options etc. if they want.
Though I'd be happy to hear your argument if you're not satisfied with my explanation.

**Comment by aucub** [comment]
> One of our main goals with Hiddify Next is to provider an easy-to-use experience for newbies and hide the complexities in more advanced sections of the app. Since these users might not know the difference between proxy, tun etc. we've used a more generalized term, “connect”. In this way, users can easily relate to the options and more demanding users will have access to more in-depth settings like service mode, config options etc. if they want. Though I'd be happy to hear your argument if you're not satisfied with my explanation.

In some cases the "Disconnect" and "Connect" text are displayed incorrectly, which may be a bug. I think it will be difficult to eliminate this bug, and using the check mark and "Disconnect" text at the same time can be misleading. Using a "Proxy" literal in the tray is meaningless, but also eliminates these problems.
![截图 2023-11-22 03-23-27](https://github.com/hiddify/hiddify-next/assets/78630225/eafe0c91-6057-46e2-9a18-ad5d66c27e52)
![截图 2023-11-22 03-23-43](https://github.com/hiddify/hiddify-next/assets/78630225/a1250f41-3e7b-4805-8937-dbac59c5c21c)
![截图 2023-11-22 03-24-28](https://github.com/hiddify/hiddify-next/assets/78630225/22bcd92c-828d-4af0-9ac6-29eb42420bed)

**Comment by problematicconsumer** [comment]
> using the check mark and "Disconnect" text at the same time can be misleading

Good observation, check mark is redundant.
We can also add another tile above connect/disconnect one with no action attached to indicate service status as “connected” or “disconnected”. It's important to keep it simple and consistent, since most commercial VPNs also use these terms and users are familiar with them.
