### ISSUE TITLE
VPN configuration not registering in iOS settings

### ISSUE THREAD

**Issue by H-Khoujani** [hiddify/hiddify-next#290]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

I built the app for iOS and changed the signing changes of the app and ran the app, but after clicking on "Tap to Connect" and going to the VPN configuration creation section and returning to the app, nothing happened, and I clicked again, I was directed back to settings. I think the VPN configuration is not being created at all.

### Reproduce the Bug

1. Start the app in debug mode
2. Import vless config with `add from clipboard`
3. tap to Connect

### Version

0.13.2 dev

### Platform/OS

iOS

### Additional Context

![p84@1704310282565](https://github.com/hiddify/hiddify-next/assets/72504271/8836137f-e38d-41cd-9a73-b430e805c1b0)

### Are you willing to submit a PR? If you know how to fix the bug.

- [X] I'm willing to submit a PR (Thank you!)

**Comment by AmirhosseinBrooklyn** [comment]
Hi Mr. Khoujani, First of all thank you for the result of your personal effort to develop HiddifyNext for iOS.
All of us have been waiting for the iOS version for months, but even I doubt that despite the feature requests and bugs of HiddifyNext for Android, Windows and MacOS, the Hiddify team has prioritized the design of the iOS version, even though it will undoubtedly be well received.
That's why I suggest that you create a repository for the iOS version and develop it yourself and other friends in the Hiddify Telegram group. It can be tested and checked by users through TestFlight.

**Comment by hiddify-com** [comment]
Dear @H-Khoujani 
It would be great if you can create PR.
We would like to progress quickly on iOS app  soon.
Thanks

**Comment by khayyamov** [comment]
Chashm 
I fixed some of iOS problems and tested them. They are working well. Awesome!

**Comment by hiddify-com** [comment]
@khayyamov Great
Would you please do PR?

**Comment by sbh96** [comment]
i am want to pr i am backend developer so its hard for me but i will help you to fix this issues too. all of us in same side

**Comment by sbh96** [comment]
https://github.com/SagerNet/sing-box-for-apple
